### ISSUE TITLE
Crash when trying to start Modpack

### ISSUE THREAD

**Issue by Th3Tobi** [InfinityRaider/AgriCraft#688] opened 2016-08-15 08:42 UTC
I wanted to add Agricraft to the AT-Launcher-Modpack R&Q's ENDLESS. Every time when I start the game it is preparing the game files and crashes when reaching the last point of preparing.
Mod-Version: 1.5.0 (also tried 1.2.1)

**Comment by RedNesto** [comment] 2016-08-15 08:45
Could you provide your latest crash report. Without, nobody can help you.

**Comment by Th3Tobi** [comment] 2016-08-15 08:55
[fml-client-latest.txt](https://github.com/InfinityRaider/AgriCraft/files/417772/fml-client-latest.txt)



Just tried with the 1.4.6 version of the mod

**Comment by RedNesto** [comment] 2016-08-15 09:11
Seems to be a duplicate of #523 .

Try with the [latest Botania for 1.7.10](http://botaniamod.net/dl.php?file=Botania%20r1.7-237.jar) and Agricraft 1.5.0

**Comment by Th3Tobi** [comment] 2016-08-15 09:20
[fml-client-latest.txt](https://github.com/InfinityRaider/AgriCraft/files/417809/fml-client-latest.txt)

Crashing again while loading :/

**Comment by RedNesto** [comment] 2016-08-15 09:27
That breaks some mods, but not Agricraft's fault anymore:

        UCHE	openmodularturrets{2.2.0-178} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.2.0-178.jar)
        UCHE	PortalGun{4.0.0-beta-5} [PortalGun] (PortalGun-4.0.0-beta-5.jar) 
        UCHE	Translocator{1.1.2.15} [Translocator] (Translocator-1.7.10-1.1.2.15-universal.jar) 
        UCHE	utilityworlds{1.0.7} [Utility Worlds] (UtilityWorlds-1.7.10_1.0.7.jar) 
        UCHE	denseores{1.0} [Dense Ores] (DENSEORES-1.5.jar) 

Does it work if you try with [Botania 237](http://botaniamod.net/dl.php?file=Botania%20r1.7-237.jar) ?

**Comment by Th3Tobi** [comment] 2016-08-15 09:30
The second log i provided was with the 237 version of Botania

**Comment by RedNesto** [comment] 2016-08-15 09:32
oops

And with [Botania 249](http://botaniamod.net/dl.php?file=Botania%20r1.8-249.jar) ?

I start tests in my side.

**Comment by Th3Tobi** [comment] 2016-08-15 09:37
Another crash with Botania 249 :(

**Comment by RedNesto** [comment] 2016-08-15 09:52
I have too.
In my side it's a `maximum range exceeded`. That means there are too many block (obviously too many  mods). If the error is the same for you, delete some mods you will not be using to free some space.

**Comment by InfinityRaider** [comment] 2016-08-15 09:58
@RedNesto is correct.

**Closed by InfinityRaider** 2016-08-15 09:58 UTC

**Comment by Th3Tobi** [comment] 2016-08-15 10:28
Worked fine for me - thanks a lot!
