### ISSUE TITLE
Resource Pack Reset by AgriCraft

### ISSUE THREAD

**Issue by oitsjustjose** [InfinityRaider/AgriCraft#595] opened 2016-03-27 14:42 UTC
Alright, so I've tested this in a control instance with Only (and without) AgriCraft, and I've been able to narrow it down as the source.

In my options.txt, my proper Resource Pack is in the list of selected resource packs - but when I launch with AgriCraft installed, it _isn't_ selected. Having to select it and reload the Resource Manager isn't the best on RAM.

Not a deal breaker for me on 16GB of ram, but if I was using my MacBook, I'd be without Resource Pack for a little while :)

**Comment by InfinityRaider** [comment] 2016-03-27 14:44
Of course, issues are always accepted, however this is a duplicate of #592

**Comment by InfinityRaider** [comment] 2016-03-27 14:45
Nevermind me, wrong issue...

**Comment by cyberpunkbln** [comment] 2016-04-05 17:21
Hi,
i have the same bug. Config okay but ressource-pack must be reassigned ingame. Delete i AgriCraft then it is okay.
thx

**Comment by RlonRyan** [comment] 2016-04-05 20:58
Yeah... I have no idea which one of the many hacks in the mod could be causing that issue... This might be something that can only be fixed with the 1.9 rendering re-write.

**Comment by InfinityRaider** [comment] 2016-06-14 11:39
Closing this since 1.8.9 has been pulled.

**Closed by InfinityRaider** 2016-06-14 11:39 UTC
Labels: 1.8.9, bug
