### ISSUE TITLE
Crash when right clicking Sprinkler with Channel in hand

### ISSUE THREAD

**Issue by pgourinchas** [InfinityRaider/AgriCraft#789] opened 2017-01-11 19:28 UTC
Hello,

First time reporting an issue here, please don't be too rude.

It looks like right clicking a Sprinkler with a Wooden Irrigation Channel in hand is making the game crash.

I have a lot of mods installed but I don't think it is related.

Agricraft version: 2.0.0-i0.3.0-a3
InfinityLib version: 0.3.0
Forge version: 12.18.3.2182
Minecraft 1.10.2

I'm not sure if this is a Agricraft issue or InfinityLib.

I put the crash report here:
[crash-2017-01-11_20.12.31-client.txt](https://github.com/InfinityRaider/AgriCraft/files/699823/crash-2017-01-11_20.12.31-client.txt)

Thank you very much for your work.

**Comment by pgourinchas** [comment] 2017-01-11 19:48
Just checked latest Agricraft version: 2.0.0-i0.4.0-a5 (InfinityLib 0.4.0) the issue is still present.

[crash-2017-01-11_20.44.39-client.txt](https://github.com/InfinityRaider/AgriCraft/files/699884/crash-2017-01-11_20.44.39-client.txt)

**Comment by InfinityRaider** [comment] 2017-01-11 20:41
Thanks for reporting, will look into it when i have time.

**Comment by RlonRyan** [comment] 2017-01-12 17:58
Duplicate of #778. Already fixed, waiting to be released.

**Closed by RlonRyan** 2017-01-12 17:58 UTC
Labels: duplicate, invalid
