### ISSUE TITLE
Log spam and Crash with 1.5.0

### ISSUE THREAD

**Issue by Neodark7** [InfinityRaider/AgriCraft#598] opened 2016-03-28 14:11 UTC
http://pastebin.com/i2ETDyrV

Since 1.5.0 ( not sure ) i get this every 10min

http://pastebin.com/i2ETDyrV

this block of lines, but like thousands of those, i can't post the log cause it's 175 000 lines long... x)

Halp plz

**Comment by InfinityRaider** [comment] 2016-03-29 10:26
I'll need the point where this started.

**Comment by InfinityRaider** [comment] 2016-03-29 16:39
I've decided I'm not going to do anything for 1.7 anymore, so I am closing this.

**Closed by InfinityRaider** 2016-03-29 16:39 UTC
Labels: 1.7.10

**Comment by Neodark7** [comment] 2016-03-29 21:16
-_- ok

**Comment by InfinityRaider** [comment] 2016-03-29 21:34
Sorry, but maintinging 3 versions in parallel is almost impossible.

**Comment by Neodark7** [comment] 2016-03-29 21:40
The 1.7.10 is the only *stable* version, and it's where people play, i see that as a player, a pack-maker and a server manager.
But you are the modder, it's your mod, your choice.

**Comment by insuusvenerati** [comment] 2016-03-29 22:19
[16:02:08] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.OutOfMemoryError: Java heap space

Seems pretty obvious what the issue is.

**Comment by InfinityRaider** [comment] 2016-03-29 22:50
Yes but that could also be due to a memory leak

**Comment by Neodark7** [comment] 2016-03-29 22:58
min 2048 / max 4096 / permgen 256

so no @insuusvenerati it's not a dumb out of memory due to poor ram allocation...

@InfinityRaider ofc you have to move on, i play on MC since alpha so i understand that, but i'm not here to report an MC1.5 or MC1.6 bug, 1.9 packs don't really exist, everybody is still playing 1.7.10... it's not the past. I don't ask you tu support 3 versions, but at least continue to support the last stable version, until you have an "1.9 official stable full release" thing...

**Comment by insuusvenerati** [comment] 2016-03-29 23:18
My point was there is no information in that error report. Would need a stacktrace or something indicating where the start of the error is.

**Comment by RlonRyan** [comment] 2016-03-30 00:18
If it's not crashing, it might just be a warning that didn't get marked with the right debug level. In that case, the overhead associated with fixing it outweighs the issue itself, regardless of it being a legacy support issue.
