### ISSUE TITLE
NPE when racking full grown sesam on stick

### ISSUE THREAD

**Issue by Fundaris** [InfinityRaider/AgriCraft#562] opened 2016-02-10 13:06 UTC
Hi i get a disconnect when I'm trying to rake a fullgrown sesam on sticks. I used the rake most time today with same steps. But didn't got any disconnect.

[NPE.txt](https://github.com/InfinityRaider/AgriCraft/files/124744/NPE.txt)

**Comment by InfinityRaider** [comment] 2016-02-10 13:35
This is a duplicate of #540

**Closed by InfinityRaider** 2016-02-10 13:35 UTC
