### ISSUE TITLE
[1.4.0] Strange Crops Behavior

### ISSUE THREAD

**Issue by Xiaminou** [InfinityRaider/AgriCraft#242] opened 2015-06-26 13:49 UTC
![2015-06-26_14 50 29](https://cloud.githubusercontent.com/assets/8670392/8377596/c841d3f8-1c12-11e5-918c-7c8006098db7.png)

Forge: 1448
Agricraft: 1.4.0
Video 1: https://drive.google.com/file/d/0B090g8mHJkCWTTRaSWtQSjk3WWc/view?usp=sharing
Video 2: https://drive.google.com/file/d/0B090g8mHJkCWUlhuSFBCRFRlTVE/view?usp=sharing

As you can see on video 1, melon works fine but does not yield anything, on video 2 carrot doesn't show growth but yields 4 carrots as it should.

Video 3: https://drive.google.com/file/d/0B090g8mHJkCWb2o3dGJBc0NwQ00/view?usp=sharing

video 3 is made using agricraft only, melon grow fine but only yielded the first time it grew, carrots work fine.

Also WAILA doesn't show if the plant can grow anymore.
Also Also How come pam's harvestcraft cotton doesn't have a mutation recipe?
Also Also Also Should Fertilized Soil from Random Things be added to the default list of Farmland compatible Soils?

**Comment by InfinityRaider** [comment] 2015-06-28 10:35
I'm failing to reproduce this issue, is anything coming up in the log? And when analyzed, what shows up under fruits in the journal. And what does NEI tell you when looking up usage of the seeds.

As for the WAILA issue I refer to #244 

I don't know why harvestcraft cotton doesnt have a mutation recipe, I probably overlooked it, I'll add it in.

I'm not going to add any more soils on my side, I've provided tools for Pack Creators to register soils, that should be sufficient.

**Comment by Xiaminou** [comment] 2015-06-28 11:22
I took the seeds from NEI, so they're 1/1/1s, Just tried analyzing them and growing them again and I still get the same bug from the melons.

Client log: https://drive.google.com/file/d/0B090g8mHJkCWTnVSbEx0NVl6VTA/view?usp=sharing

**Comment by InfinityRaider** [comment] 2015-06-28 11:32
Nothing useful in the log, but does it show the fruits in the journal:
http://puu.sh/iFE3G/3142e30420.png

And does NEI tell you the fruits:
http://puu.sh/iFE5d/b3207af41f.png

**Comment by Xiaminou** [comment] 2015-06-28 11:41
Analyzed the seeds with the journal in the analyzer, and NEI shows me the recipe for the melon, tried growing it again, this time it yielded melon twice, then nothing.

log: https://drive.google.com/file/d/0B090g8mHJkCWV0gzdk9Ed1d3UlE/view?usp=sharing

**Comment by homemmakako** [comment] 2015-07-02 02:55
I'm having the exact same issue (the one with melons and pumpkins). I tried using nothing but Agricraft and still got the same results: I got one melon on the first try but after that, nothing. Here is the log of the instance with solely agricraft 1.4.0 Alfa (and btw, yes, the product shows up in the journal)

Log: http://pastebin.com/qeexYhUx

**Comment by InfinityRaider** [comment] 2015-07-03 19:36
The melon stuff has been fixed. I can't replicate the carrots not rendering though. Can you use the agricraft debug item on the carrots that arent rendering and give the information it gives?

**Comment by Xiaminou** [comment] 2015-07-03 21:05
![2015-07-03_23 02 11](https://cloud.githubusercontent.com/assets/8670392/8504783/bbb4c5e4-21d7-11e5-8420-b013d03abd76.png)
![2015-07-03_23 02 14](https://cloud.githubusercontent.com/assets/8670392/8504784/bbd7d3cc-21d7-11e5-92ec-b23244e520f3.png)
![2015-07-03_23 02 31](https://cloud.githubusercontent.com/assets/8670392/8504785/bbd9af62-21d7-11e5-915e-e72ef25e8143.png)

Looks like there is a inconsistency between what the client see and what the server see

**Comment by InfinityRaider** [comment] 2015-07-03 21:13
So clientside it first says it has a plant and the metadata is 2, and then it says that it doesn't have a plant?

**Comment by Xiaminou** [comment] 2015-07-03 21:16
Clientside the infos correspond to what you see, and serverside the infos are what it actually is.
The first one was when carrots weren't fully grown for both client and server, the second one was when the carrot is fully grown for the server and disappeared for the client.

**Comment by InfinityRaider** [comment] 2015-07-03 21:29
Yes I know what the difference is between client and server, I just didn't understand why the screenshots showed different data clientside.

Can you replicate this behaviour on any of the other crops?

**Comment by Xiaminou** [comment] 2015-07-03 21:30
Sugar Cane has the same problem.

**Comment by InfinityRaider** [comment] 2015-07-03 21:33
Wait I just noticed the MFR harvesters and I think those harvesters might have something to do with it (I derped up mod integration when I rewrote some things).
Has it occurred on any crops that are outside the range of a harvester?

(mushrooms need darkness btw)

**Comment by Xiaminou** [comment] 2015-07-03 22:08
Yes it happens outside the Harvester's range too.
and the mushrooms have the same problem (which is why they didn't seem to grow when I tried growing them in the dark the first time, but they actually do grow in the dark).

**Comment by InfinityRaider** [comment] 2015-07-04 07:56
Is this SSP or SMP? And does it also happen in an instance with only agricraft?

**Comment by Xiaminou** [comment] 2015-07-04 07:57
SMP, in an SSP instance with only agricraft it doesn't. haven't tried SMP with only agricraft because I'm lazy.

**Comment by InfinityRaider** [comment] 2015-07-04 09:33
Ill try to replicate it in an SMP environment, I've only tried in SSP so far.

**Comment by Bomber57** [comment] 2015-07-10 12:26
Just want to say that I am having the same issue in SSP with my brown mushrooms. They are growing in a dark room as they should, but visually appear to be stuck at 0% growth (WAILA also reads them at 0%) and if I right click the crop it just turns invisible. If I use bone meal the crop does not disappear, so I'm not exactly sure that is causing the rendering issue.

Sorry if this is a redundant post, I just thought that providing more evidence/another report of this bug happening would help.

**Comment by InfinityRaider** [comment] 2015-07-10 15:30
It's certainly not a redundant post, there must be something that I'm missing because I am failing to reproduce this. Really want it fixed, so the more details, no matter how irrelevant they might seem, the better.

**Comment by spocane** [comment] 2015-07-10 23:55
I too am having similar issue but seems to be with all crops. they mostly seem to grow normal, then when you harvest them they no longer show that they are mature, but using bonemeal/watering can you can harvest them again, but randomly the crop dissapears and WAILA says "No Crop". relogging makes them reappear showing all correct info. Both SSP and SMP. 

I am no coder, but it definatley seems to be a sync issue between client and server.

forge-1.7.10-10.13.4.1481
Agricraft-1.4.0 beta 4
lots of other mods

**Comment by Enilo** [comment] 2015-07-11 01:41
Just thought I should add in here that I have the same problem. The seeds that do work normally for me are regular seeds and then melon and pumpkin seeds. Carrot, potatoes, sugarcane, cactus and all the various flower ones do not work. This meaning that they first show up as 0% percent for me. When interacted with they turn invisible. I can break them and get back the seed and the produce if such has grown while invisible. 

While invisible I can still use them to mutate and spread to other crops. It seems to be a purely visual problem for me since I can still grow everything..

**Comment by InfinityRaider** [comment] 2015-07-11 18:03
I managed to replicate it outside my dev environment, but only after closing and reloading the world.
I'll try to do that in my dev env as well and find out wtf is going on.

**Comment by InfinityRaider** [comment] 2015-07-12 15:43
I finally found it, it was something really stupid, but it should be fixed now.

**Closed by InfinityRaider** 2015-07-12 15:43 UTC
Labels: bug, research needed
