### ISSUE TITLE
Wooden Water Tank cannot accept water

### ISSUE THREAD

**Issue by Armigus** [InfinityRaider/AgriCraft#412] opened 2015-10-09 14:16 UTC
I've tried XU water node and TE portable tank.  The tank simply will not accept water.  Breaking and replacing does no good.  Are you required to have more than one now?

Version 1.4.0.

Multiple tanks seem to work with the TE portable tank, perhaps because of raw transfer speed.  Can someone check this?

**Comment by InfinityRaider** [comment] 2015-10-09 22:15
I should ahve to verify this, tank code changed, but if this doesn't work anymore I'll look into fixing it.

**Comment by InfinityRaider** [comment] 2015-10-18 10:47
Was able to reproduce this, single tanks won't accept water due to their multiblock status being initialized before the coordinates where, this is fixed now, thanks for reporting.

**Closed** 2015-10-18 10:50 UTC
Labels: bug

**Comment by mrammy** [comment] 2015-10-20 21:54
Just as a quick note this should probably fix an issue i was having with single tanks not filling while it was raining in 1.4.1 version from Curse. Thanks for the fix!
