### ISSUE TITLE
Crash:  java.lang.NullPointerException: Tesselating block model

### ISSUE THREAD

**Issue by FraukeS** [InfinityRaider/AgriCraft#770] opened 2016-12-27 17:20 UTC
I get a crash with java.lang.NullPointerException: Tesselating block model when exploring near a village in a new MC world. This has happened 5 times so far in 2 different worlds.

I also noticed that the melon and pumpkins crops in the greenhouses use the wheat texture, but this could be a texture pack error.

Full crash log:  http://pastebin.com/NZW2g32S

**Comment by Eufranio** [comment] 2016-12-27 19:28
Update InfinityLib and AgriCraft, this should be fixed.

**Comment by FraukeS** [comment] 2016-12-27 19:37
I have agricraft-2.0.0-0.4.0-a5  and infinitylib-0.4.0 , the latest available on Curse.

Where can I find newer versions?

**Comment by MidnightsFX** [comment] 2017-01-02 01:07
Also seeing this with infinitylib-0.4.0 and agricraft-2.0.0-0.4.0-a5 is there a newer build that fixes this? Nothing newer than a5 is listed on curseforge.

**Comment by ViperZeroOne** [comment] 2017-01-02 03:23
Confirming this issue in infinitylib-0.4.0 and agricraft-2.0.0-0.4.0-a5

We've got 5 crash logs across 3 computers showing the same error.

**Comment by Eufranio** [comment] 2017-01-02 03:23
Hmmm, since I updated the crash stopped for me, do you know how to reproduce?

**Comment by ViperZeroOne** [comment] 2017-01-02 05:31
No idea how to reproduce.  We removed Agricraft (temporarily) and the client crash is gone.  The crashes seemed to be more severe (if not always) when we were at or close to a village.

**Comment by ViperZeroOne** [comment] 2017-01-02 05:36
Crash reports regarding the client crashing.  These reports came from two separate computers located in two different cities;

Computer 1:

[crash-2017-01-01_21.46.04-client.txt](https://github.com/InfinityRaider/AgriCraft/files/680417/crash-2017-01-01_21.46.04-client.txt)
[crash-2017-01-01_22.10.45-client.txt](https://github.com/InfinityRaider/AgriCraft/files/680418/crash-2017-01-01_22.10.45-client.txt)

Computer 2:

[crash-2017-01-01_21.13.03-client.txt](https://github.com/InfinityRaider/AgriCraft/files/680419/crash-2017-01-01_21.13.03-client.txt)
[crash-2017-01-01_21.45.02-client.txt](https://github.com/InfinityRaider/AgriCraft/files/680420/crash-2017-01-01_21.45.02-client.txt)

**Comment by FraukeS** [comment] 2017-01-02 10:04
I looked up the location in the error log. 
It was a village greenhouse with lapender seeds on a cropstick (0% cannot grow) next to 2 empty cropsticks and 6 other Agricraft crops.

**Comment by SpartanSamuel** [comment] 2017-01-02 15:57
I'm having the same issue but when my wife is building her water tank. The crash logs center around the tank being rendered as well. She can't add valves to the tank either.

Water Tank Crash: http://pastebin.com/UZ5WhzmA
Valve Crash: http://pastebin.com/EwRUCzCm

**Comment by ViperZeroOne** [comment] 2017-01-02 16:17
The first village we experienced crashes at didn't have a water tank, but the second one where we experienced much more crashes did.

**Comment by InfinityRaider** [comment] 2017-01-02 21:02
The tank crash is something else and is an easy fix, idk about the NPE one though...

**Comment by Candlemancer** [comment] 2017-01-14 01:41
This crash seems to only happen for me if I've got some Agricraft plants growing adjacent to some vanilla plants. Maybe some other folk seeing this issue could check if reorganizing your farms to keep Agricraft and vanilla crops segregated fixes the issue for you?

**Comment by FraukeS** [comment] 2017-01-15 11:10
Was near a village in a newly generated world for 40+ minutes in the new 0.5.0-a6 version.
No crashes.
Also no more free high tier seeds, but those were OP anyway.

**Comment by petulko8080** [comment] 2017-01-16 11:21
latest release: agricraft 0.5.0-a6, infinitylib 0.5.0
got crash with Description: Tesselating block model 
happened randomly only when trying to harvest pumpkin (at least 3 from 9 plants crashed  everytime) , harvesting wheat without problem, also my custom seed (hemp from immersive engineering) harvested without problem

http://pastebin.com/QCYjcSU9

**Comment by Tukanen** [comment] 2017-01-31 13:16
Just happened to me, agricraft 0.6.0-a9 and infinitylib 0.6.0

http://pastebin.com/HTux1CNU

in this case it was a crossed cropstick standing freely in a line of crossed cropsticks

no interactions with anything farmable was being done at the time, merely running along. I HAVE tinkered a bit with the json files though.

**Comment by RlonRyan** [comment] 2017-02-02 16:21
This might be an issue with threading, in a10 I added some checks that will tell if that's the issue. If so, I would need new crash logs from a10. Thank you all for your patience.

**Comment by 23Link89** [comment] 2017-02-03 17:52
So what should I do if I'm running 1.7.10 and is having this issue?

**Comment by RlonRyan** [comment] 2017-02-03 18:55
If your on 1.7.10, then you should be having a undefined class error since the class that is causing this is only in the 1.10+ releases.

**Comment by RlonRyan** [comment] 2017-02-03 18:56
In other words 1.7.10 is an unrelated issue that is not priority, given that we want to focus on keeping up with 1.10.2. Thanks for checking old issues before creating a new one though!

**Comment by Hylkevd** [comment] 2017-02-05 10:46
I've also got an crash with tesselating block models, here's the paste of my crash report:

http://pastebin.com/UrAMvugj

agricraft-2.0.0-0.6.0-a10
infinitylib-0.6.1
forge-12..18.3.2185
optifine_1.10.2_HD_U_D6

**Comment by RlonRyan** [comment] 2017-02-06 01:12
@Hylkevd thanks for the updated log! I think I managed to pin down the line that was causing the error. I had to rewrite the entire function, but I think I have the error fixed in InfinityLib-0.6.2. 

Of course, this bug seems to have an uncanny ability to persist, so if you do get it to pop up again in the new version a new log would again be very appreciated.

**Comment by Hylkevd** [comment] 2017-02-06 07:36
No problem, thank you and Infintyraider for the awesome mod!

**Comment by RlonRyan** [comment] 2017-02-10 21:05
So... It would sound like this issue is fixed? As there have been no new reports in 5 days, I am closing this issue. If it does reoccur, feel free to reopen.

**Closed by RlonRyan** 2017-02-10 21:05 UTC
Labels: bug, client
