### ISSUE TITLE
Greenhouses don't have plants

### ISSUE THREAD

**Issue by urbanlime** [InfinityRaider/AgriCraft#844] opened 2017-02-18 17:39 UTC
I know in previous versions greenhouses had plants spawn in them but in the pack I'm currently working on they don't. I was wondering if there was any way to fix this.

**Comment by Nanianmichaels** [comment] 2017-02-18 17:51
Please check #840 to see if it's the same issue. It looks like it might be.

**Comment by RlonRyan** [comment] 2017-02-19 23:19
Dupe of #840.

**Closed by RlonRyan** 2017-02-19 23:19 UTC
Labels: duplicate
