### ISSUE TITLE
Duplicate Seeds 

### ISSUE THREAD

**Issue by urbanlime** [InfinityRaider/AgriCraft#845] opened 2017-02-19 20:59 UTC
When I create jsons for the seeds everything works properly, but there are two versions of seeds in jei. I'm trying to create mystical agriculture compatibility and this is specifically happening with the inferior infernium seeds(I haven't done the others yet). The issue with this is the version that is craftable is not plantable on cropstick, nor will it work with mutations. Any help with this issue would be greatly appreciated, thank you.

**Comment by Ravin890** [comment] 2017-02-19 21:19
There is a lot of issues concerning the seed jsons. Look around and there are a few. The main thing is that the files are more or less finicky

**Comment by RlonRyan** [comment] 2017-02-19 23:18
This seems to be a general issue with mystical agriculture. I think that mystical agriculture does something atypical with their items, so that AgriCraft can't resolve them properly. I would recommend looking into your log files to see what AgriCraft is reporting.

**Comment by RlonRyan** [comment] 2017-02-19 23:24
Duplicate of #838.

**Closed by RlonRyan** 2017-02-19 23:24 UTC

**Comment by urbanlime** [comment] 2017-02-20 00:50
How do I access my log files and what do I look for? I'm not a coder so this is all new to me.

**Comment by Ravin890** [comment] 2017-02-20 00:56
in the main folder for the profile (if you click edit profile and open dir you will get to there from old launcher, not sure of new one) and there is a folder named logs
