### ISSUE TITLE
Cannot craft channels/tanks with Oak planks

### ISSUE THREAD

**Issue by tfox83** [InfinityRaider/AgriCraft#858] opened 2017-03-08 17:20 UTC
All other vanilla planks seem to work except oak.
I can work around this with CT in FTB Beyond, but wanted to give you a heads up!

OP: https://forum.feed-the-beast.com/threads/cant-make-water-tank-or-water-channel.220510/#post-1843850

Thanks!

**Comment by RlonRyan** [comment] 2017-03-09 00:18
Duplicate of #724. Thanks for the update though!

**Closed by RlonRyan** 2017-03-09 00:18 UTC
Labels: duplicate
