### ISSUE TITLE
Standalone crops Growth rate multiplier appears to be ignored

### ISSUE THREAD

**Issue by zj44** [InfinityRaider/AgriCraft#586] opened 2016-03-13 13:10 UTC
I use AgriCraft and Hunger Overhaul and I like to slow down the crop growth rate significantly -- at my settings, a vanilla crop would take 14 in-game days to grow. I'd love to use AgriCraft, but it seems like crops planted with AgriCraft ignore the 'Growth rate multiplier' option entirely -- if I plant a potato using AgriCraft seeds, I can expect this potato to be grown in a day. No matter what I set the growth rate multiplier to, I see no difference in the growth speed.

**Comment by InfinityRaider** [comment] 2016-03-13 14:16
That should not be the case, because: https://github.com/InfinityRaider/AgriCraft/blob/7ec8e3be2e8fdfc089310ecbb7b81314dbe9805a/src/main/java/com/infinityraider/agricraft/blocks/BlockCrop.java#L111-L117

**Comment by InfinityRaider** [comment] 2016-03-13 14:18
Wait, are you talking about crops growing in crop sticks or just on their own?

**Comment by zj44** [comment] 2016-03-13 15:36
On their own. I think the same thing is going on with crop sticks, but I didn't plant any yet because of the issue.

**Comment by InfinityRaider** [comment] 2016-03-13 15:48
Ok I see where the issue is, It used to be the lower the value the higher the growth speed, but I flipped it around because it made mroe sense but I forgot to also flip it around for standalone crops: https://github.com/InfinityRaider/AgriCraft/blob/7ec8e3be2e8fdfc089310ecbb7b81314dbe9805a/src/main/java/com/infinityraider/agricraft/blocks/BlockModPlant.java#L214

My mistake.

**Comment by zj44** [comment] 2016-03-13 16:00
Cool that you were able to figure it out. Thanks for the help -- looking forward to the fix!

**Comment by InfinityRaider** [comment] 2016-03-29 16:40
This will be fixed in an upcoming release for 1.9 (as its cause is in base code which will not change), don't expect a fix for 1.7

**Closed** 2016-06-14 11:49 UTC
Labels: bug
