### ISSUE TITLE
Breaking tanks cause internal server error.

### ISSUE THREAD

**Issue by Kubuxu** [InfinityRaider/AgriCraft#262] opened 2015-07-08 08:23 UTC

**Comment by InfinityRaider** [comment] 2015-07-08 16:47
Crash report/log?

**Comment by Kubuxu** [comment] 2015-07-08 16:58
Nothing, just internal server error showing on client screen.

**Comment by marcin212** [comment] 2015-07-08 16:59
I play with @Kubuxu. It was caused by #263

**Comment by InfinityRaider** [comment] 2015-07-08 17:00
If its the same crash, I'm going to close this.

**Closed by InfinityRaider** 2015-07-08 17:00 UTC
