### ISSUE TITLE
FPS loss with planted seeds

### ISSUE THREAD

**Issue by Silvrus** [InfinityRaider/AgriCraft#797] opened 2017-01-15 09:39 UTC
Agricraft 2.0.0-0.5.0-a6

Bred seeds to 10/10/10, then planted a 9x9 field and FPS tanked from 120 to ~30, with regular drops to 0-5 during visual growth ticks. Removing crops returned FPS to normal 120. No CTD.

**Comment by RlonRyan** [comment] 2017-01-22 17:25
What does CTD mean?

**Comment by TehNut** [comment] 2017-01-22 17:29
Crash to Desktop

**Comment by RlonRyan** [comment] 2017-01-22 17:30
Thanks @TehNut.

**Comment by RlonRyan** [comment] 2017-01-22 17:44
@InfinityRaider This seems more up your alley...

**Comment by Nodlehs** [comment] 2017-01-23 13:56
Can confirm, I've got massive fps loss with any 10/10/10 crops. Triple checked that it is indeed Agricraft crops causing issue. Thanks for the continued updates guys :)

**Comment by RlonRyan** [comment] 2017-01-24 00:05
Is it just 10/10/10 crops?

**Comment by Nodlehs** [comment] 2017-01-24 14:56
I'll try to do some testing tonight or tomorrow and find out.

**Comment by Silvrus** [comment] 2017-01-24 18:07
Sorry, didn't see the notifications. I noticed some FPS hits while breeding, but it wasn't until I planted a field of 10/10/10 that it became unplayable. I first disabled the sprinkler thinking it was the particles, but it didn't help. When I broke that field the FPS went back to normal. I'm assuming it's something to do with the growth ticks, maybe that redraw thing I've heard about? There were a couple of other farms that weren't Agricraft, all within chunk boundaries with no machines or tanks, etc.

**Comment by RlonRyan** [comment] 2017-01-24 18:11
Huh... Perhaps at 10/10/10 the growth ticks get applied too frequently? Does the fps still go down if all the plants are fully grown?

**Comment by Silvrus** [comment] 2017-01-24 18:27
I'll test and let you know.

**Comment by Silvrus** [comment] 2017-01-24 19:27
Confirmed. New world, used the irrigated greenhouse farm (which didn't spawn any crops for some reason) and planted 2 5x5 fields of 10/10/10. During growth cycle game was highly lagged, once the crops were all grown the FPS returned to normal. Ran a profile while crops were growing, http://pastebin.com/NMVTXDce.

**Comment by TehNut** [comment] 2017-01-24 20:43
Just curious, I'd you use 1/1/1 crops and use the gamerule command to speed up the tick cycle, do you notice it as well?

**Comment by Silvrus** [comment] 2017-01-24 20:55
Is that /gamerule randomTickSpeed ? What should I set it to?

**Comment by RlonRyan** [comment] 2017-01-24 21:19
Well the normal tps is 3 so, that's reasonable to lag a bit there... The fact that only the maxed plants cause the lag with normal tps is the interesting result here.

**Comment by Silvrus** [comment] 2017-01-24 21:48
Could it be the lower tier plants have lower growth rate so not as many, (what is it, blockstate changes?) happening at the same time? Higher tier plants grow faster so more updates, exacerbated by anything speeding up crop growth?

**Comment by InjuredWolf** [comment] 2017-01-28 13:05
Low tiers with Actually Additions worms also cause this. Haven't tested with higher tiers but I imagine it would be worse.

**Comment by MokahTGS** [comment] 2017-02-05 20:53
I'm seeing very noticeable FPS issues with a 9x9 field of 1/1/1 plants.  I'm not sure 10/10/10 is the only issue.

**Comment by TehNut** [comment] 2017-02-05 21:11
Here is a video showing the issue. http://streamable.com/jv89m

That is a 9x9 field of default (1/1/1) seeds.

**Comment by RlonRyan** [comment] 2017-02-05 22:49
Wow that is quite major... It might take a fair bit of investigating...

**Comment by RlonRyan** [comment] 2017-02-06 01:21
Oops... wrong button.

(I guess it is just a subconscious fear of the rendering code...)

(Why do we have to have rendering code?)

**Comment by Waisse** [comment] 2017-02-08 11:34
I also have the same issue. There's is a slight frame freeze when I place/break blocks in a chunk with agricraft crops. 

Not really related but it seems memory keep increasing and ultimately cap when I play with agricraft crops nearby (need more testing thought).

**Comment by InfinityRaider** [comment] 2017-02-08 20:25
Can someone try with smooth lighting disabled.
I do think that this will be the cause, because this has to be false (https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/infinityraider/agricraft/renderers/blocks/RenderCrop.java#L113)

**Comment by TehNut** [comment] 2017-02-09 02:14
With smooth lighting disabled, the issue still occurs as in the video.

**Comment by Thyriel** [comment] 2017-02-17 03:15
I have the same problem then Waisse (a10 Agricraft version) when using agricraft on a server. Block updates in a chunk with agricraft crops have a delay and client memory keeps increasing until it hits the cap (which only takes like 2minutes), only 1/1/1 wheat seeds planted.
I think the earlier FPS drops are just related to that memory leak, as soon as it hits the cap the FPS decrease a lot because the game can't keep up.
Interestingely it's only affecting the client memory. Server memory is still at normal usage.

**Comment by Rudy2D2** [comment] 2017-02-23 05:09
I concur with Thyriel as I also have an issue with memory. It caps after a few minutes in game, causing game to lock, but only in a world with agricraft crops planted. And it is no longer an issue in a world when I remove them.

**Comment by Thyriel** [comment] 2017-02-23 06:03
Any idea / ETA on a fix for this ? I'd really love to integrate agricraft into my modpack, but this bug makes it totally unuseable

**Comment by RlonRyan** [comment] 2017-02-23 20:04
This is a tricky one... I'd have to dive into @InfinityRaider's InfinityLib...

**Comment by Doomathon** [comment] 2017-02-28 17:54
While it's no universal fix, the framerate issues disspear on my system when I set B:alwaysSetupTerrainOffThread=true in the forge config file. Just adding that in case it assists in narrowing down the source of the issue

**Comment by RlonRyan** [comment] 2017-03-01 03:28
It might be in part due to memory churn from the TransformationMatrixes.

**Comment by cortus** [comment] 2017-03-04 16:27
I am experiencing this issue as well.  I kind of freeze up every 5 or so seconds when crop sticks are in the area.  It also freezes each time a block is broken.  When crop sticks are pulled up, the freezes ceases to exist.  Turning smooth lighting off has no effect on this issue.

**Comment by RlonRyan** [comment] 2017-03-04 18:00
I think that it is a memory churn issue. We implemented our own tessellation matrix and didn't use an object pool in the background, to the point that hundreds of double arrays are created and released every few seconds.

**Comment by cortus** [comment] 2017-03-04 21:50
So anything a regular guy like me can do to make it better?

**Comment by Thyriel** [comment] 2017-03-09 18:31
Nothing better in the new a11 version. Still unplayable

**Comment by RlonRyan** [comment] 2017-03-09 18:55
What version of forge are you on?

**Comment by Thyriel** [comment] 2017-03-10 18:21
Forge 2239

**Comment by RlonRyan** [comment] 2017-03-12 18:56
I don't know how to fix this... I would need the help of someone good at working with the MineCraft rendering system. Overcoming the memory churn is just too far beyond me...

**Comment by RlonRyan** [comment] 2017-03-12 21:49
Fixed in 2.0.0a12. Was caused by faulty caching mechanism in InfinityLib.

**Closed by RlonRyan** 2017-03-12 21:49 UTC
Labels: client, research

**Comment by h0m3us3r** [comment] 2019-01-26 03:36
Any chance the fix could be implemented for 1.5.0? (it is the latest one that supports 1.7.10)
