### ISSUE TITLE
NullPointerException when harvesting wheat, but only sometimes...

### ISSUE THREAD

**Issue by zackeezy** [InfinityRaider/AgriCraft#780] opened 2017-01-04 19:25 UTC
http://pastebin.com/wcT1q0p2
It also seems to not stack the wheat I get from the crops with the wheat already in my inventory for some reason.  I assume they have some slight difference in item IDs.  But the real issue is is the NullPointerException.  It seems when I harvest too quickly it can't keep up and throws an exception. 

Minecraft Version: 1.10.2
Agricraft Version: 2.0.0-0.4.0-a5
Froge version: 12.18.3.2185

**Comment by RlonRyan** [comment] 2017-01-06 20:08
Duplicate of #770, it would seem.

**Closed by RlonRyan** 2017-01-06 20:08 UTC
