### ISSUE TITLE
osmium nuggets added when mekanism is installed lack recipe for ingot

### ISSUE THREAD

**Issue by kotoroshinoto** [InfinityRaider/AgriCraft#137] opened 2015-03-16 09:14 UTC
should have the 3x3 nugget-> ingot recipe, but for some reason it isn't there.

**Comment by kotoroshinoto** [comment] 2015-03-16 09:18
Might be that I was using an outdated version. I'll update and see if the issue remains.

**Comment by InfinityRaider** [comment] 2015-03-16 17:03
Definatly not due to versioning, as it's been ages since I changed something about recipe code, I'll fix it.

**Comment by InfinityRaider** [comment] 2015-03-16 17:25
I can confirm, its happening in my dev env as well, my guess is it's something to do with Osmium not being oredicted correctly.

**Comment by kotoroshinoto** [comment] 2015-03-16 18:15
It probably ISN"T oredicted correctly. Should I take the liberty of raising that issue with Mekanism devs?

**Comment by InfinityRaider** [comment] 2015-03-16 18:26
It is registered, I think its being registered too late, but I'm not sure. I'll check my code first

**Comment by BBoldt** [comment] 2015-03-23 00:30
Just sharing this short minetweaker script for anyone else that comes across this issue before the official fix is out:

```
// Osmium fix
recipes.addShapeless(<Mekanism:Ingot:1>, [<ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>]);
recipes.addShapeless(<AgriCraft:nuggetOsmium> * 9, [<ore:ingotOsmium>]);
```

**Comment by BBoldt** [comment] 2015-03-31 21:09
Hilariously, that script actually causes server crashes whenever someone interacts with the nuggets. 

Do not use.

**Comment by InfinityRaider** [comment] 2015-04-01 07:11
What, how? Can you give a stacktrace please?

**Comment by BBoldt** [comment] 2015-04-01 08:27
It was happening on a server a friend was running, I didn't think to get logs as it was something I caused with minetweaker. I suspect it was because I used the oredict osmium ingot, adding the same recipe you add, somehow making things more broken.

Honestly i'm not sure, I just disabled the script.

**Comment by InfinityRaider** [comment] 2015-04-01 10:06
Adding duplicate recipes shouldn't break stuff afaik

**Comment by InfinityRaider** [comment] 2015-04-02 12:25
Fixed in rewrite

**Closed by InfinityRaider** 2015-04-02 12:25 UTC
Labels: bug

**Comment by tethlah** [comment] 2017-06-09 02:24
So I've updated to 2.0.0-0.10.0-a18 and this issue still exists, you can't do anything with the osmium ingots.
