### ISSUE TITLE
water tower height

### ISSUE THREAD

**Issue by Drake2312** [InfinityRaider/AgriCraft#787] opened 2017-01-09 03:44 UTC
So i am unsure as to if this was changed with the 1.10.2 release, but in the 1.7.10 i was able to stack the water towers on top of each other and they where included within the multiblock structure, but after using the water towers in the 1.10.2 version (completely fresh world) whenever i try to do this i am unable to, i have tried with a single block , a 2x2 and a 3x3 and whenever i try in any of these configurations the first layer becomes the individual tank blocks, sending this in as i am unsure if this is a bug or an intended feature, also when trying to place the wooden flow valve my game crashed initially and then after that i was unable to load the world, and finally after removing he mod to re-enter my world i was unable to break blocks without the correct tool until i put the mod back into the game, i have included two crash reports the 
[initial crash.txt](https://github.com/InfinityRaider/AgriCraft/files/692731/initial.crash.txt) ([hastebin](https://hastebin.com/kolefaqelo.pas))
[after re inputting the mod.txt](https://github.com/InfinityRaider/AgriCraft/files/692732/after.re.inputting.the.mod.txt)

**Comment by Drake2312** [comment] 2017-01-09 11:36
ok so, removing the config file allowed me to remove the mod without any problems to gameplay

**Comment by RlonRyan** [comment] 2017-01-10 22:37
What do you mean removing the config file?

**Comment by RlonRyan** [comment] 2017-01-10 22:40
Nevermind dupe of #770.

**Closed by RlonRyan** 2017-01-10 22:40 UTC
