### ISSUE TITLE
[ALPHA] Crop issues

### ISSUE THREAD

**Issue by hron84** [InfinityRaider/AgriCraft#310] opened 2015-08-02 20:05 UTC
So, I cannot decide it is a part of the new crop/harvesting system or it's just my fault, but sometimes when right-click harvesting a crop, it drops the crop, the product and the seed too (but sometimes just the crop and the product, but not really reprduducible). However, if I left-click a fully-mature crop it does not drop the seed. As my discovers revealed, these problems  can be reproduced mostly with sugar canes and cacti, so I cannot enhance them since I cannot get the enhanced seeds to analyze. 

I will update as I cross-breed more and more seeds what I can discover with this issue.

Update1: harvesting works correctly if i do it anything other than an empty hand.

**Comment by InfinityRaider** [comment] 2015-08-02 20:55
With or without Hunger Overhaul?

**Comment by hron84** [comment] 2015-08-03 06:40
Without HO, Pam's Harvest or any other harvesting-affected mod.

**Comment by InfinityRaider** [comment] 2015-08-03 15:28
Its very much possible, I made it extend another class and I seemed to have overlooked at fxing some things. I'll have a look at it.

**Comment by InfinityRaider** [comment] 2015-08-03 15:53
I can't seem to replicate, does it happen in an instance with only agricraft as well?

**Comment by hron84** [comment] 2015-08-04 08:52
I'll check it tonight. If it does work, I'll send you a mod list.

**Comment by InfinityRaider** [comment] 2015-08-10 15:27
Any news?

**Comment by hron84** [comment] 2015-08-11 15:29
Ohh, sorry, I were sick and after that I went to enjoy my holiday. Tonight I'll send you a mod list.

**Comment by InfinityRaider** [comment] 2015-08-11 16:12
So you're still having the issue?

**Comment by hron84** [comment] 2015-08-12 01:19
I updated to beta-1 and it seems previous issues are solved, but I now have another issue: if i harvest a sugar cane, and I try to harvest an another sugar cane using the sugar cane item on the crop sticks with mature sugar canes, the crop stick consumes a sugar cane, one per right click but the mature crop does not become harvested (does not change state). Other plants are now looks fine.

This is the mod list: https://gist.github.com/hron84/124f641811f5a13ebc94

Note: this list is a bit older and contains the older (alpha-6) AgriCraft but I did not touched other thing than updating AgriCraft, so this list matters anyway.

**Comment by InfinityRaider** [comment] 2015-08-12 09:22
The sugarcane thing might be a bug because sugarcane is now direcly plantable.
And no, you should be able to harvest with anything, I'll try to reproduce it once more.
The weeds consuming crop sticks is a config option, but it should be off by default.

**Comment by hron84** [comment] 2015-08-15 14:46
@InfinityRaider errm... I do not want to make this issue more difficult than it should, so I promise I will open a new issue if it is definitelly a bug. Is it possible the new version makes weed spread very wild way? I do not check my garden every single time, but I definitely remember I did not left any weed-infected crop in the garden, however after I opened the game today, half of my garden overtaken by weed. I have backup from every seed, but it's definitelly annoys me, especially because I had on a good way to make a 10/10/10 sugarcane and all of my in-progress sugarcanes are gone.

**Comment by InfinityRaider** [comment] 2015-08-15 14:50
Nothing changed with weeds.

**Comment by hron84** [comment] 2015-08-15 14:58
Hmmm... then I file an another bug.

**Comment by InfinityRaider** [comment] 2015-08-15 16:00
Closing because all issues seem to have been resolved

**Closed by InfinityRaider** 2015-08-15 16:00 UTC
