### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by Tyrantin** [InfinityRaider/AgriCraft#882] opened 2017-03-24 09:46 UTC
I am creating a mod pack and I am having an issue with crafting all the irrigation items. I have gone through all of the configs to find the problem to no avail. was wondering if you could take a look at the configs for me and help.

**Comment by RlonRyan** [comment] 2017-03-25 23:52
Duplicate of #783

**Closed by RlonRyan** 2017-03-25 23:52 UTC
Labels: duplicate
