### ISSUE TITLE
self-mutations for increased crop stats don't seem to work

### ISSUE THREAD

**Issue by kotoroshinoto** [InfinityRaider/AgriCraft#121] opened 2015-03-09 03:54 UTC
nothing happens at all when there are 1,2,3 or 4 of the same crop surrounding a cross-crop

**Comment by InfinityRaider** [comment] 2015-03-09 12:44
Are they mature, do they have enough light, is it the correct soil, is the (if needed) base block present, ...

**Comment by kotoroshinoto** [comment] 2015-03-09 14:59
On 3/9/2015 8:44 AM, InfinityRaider wrote:
>
> Are they mature, do they have enough light, is it the correct soil, is 
> the (if needed) base block present, ...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/InfinityRaider/AgriCraft/issues/121#issuecomment-77846375>.
>
tested with potato & dirt in open air with path to sun under a sprinkler.

M. Gooch


---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by InfinityRaider** [comment] 2015-03-10 07:35
To be sure, they are on cropsticks right?

**Comment by kotoroshinoto** [comment] 2015-03-10 07:38
yes i disabled vanilla farming mechanics in the configs

**Comment by InfinityRaider** [comment] 2015-03-10 07:44
Hmmm, this is quite hard to debug, replace the crops, bonemeal all of them to maturity, then bonemeal the crosscrop.
Also can you send me a screenshot of the setup?
I guess some mod is denying growth ticks.

**Comment by kotoroshinoto** [comment] 2015-03-10 08:07
its allowing me to bonemeal the other crossbreed things, but the self-improvement ones simply don't.

i'll grab you an image when i can, i just purged my worlds lol.

**Comment by InfinityRaider** [comment] 2015-03-10 08:08
You can't bonemeal the corsscrops?

**Comment by kotoroshinoto** [comment] 2015-03-10 08:10
I can but nothing happens at all.

When i bonemeal the crosscrops for a cross breed rather than a 
self-breed then THAT produces an output (though sometimes it seems not 
to work on the first try or two, even though I set the config to allow it)

**Comment by InfinityRaider** [comment] 2015-03-10 08:12
Did you set the config mutation chance to 100%? Because that will cause a mutation every growth tick and spreads will never occur.

**Comment by kotoroshinoto** [comment] 2015-03-10 08:13
let me check

**Comment by kotoroshinoto** [comment] 2015-03-10 08:14
seems like it IS set to 100%

That probably explains it

**Comment by InfinityRaider** [comment] 2015-03-10 08:16
The way that works is every growth tick it checks if a plant wants to mutate or spread, if a mutation is triggered, but it can't mutate nothing will happen of course. Set it to about 50-60 if you want higher chances and check if it spreads then.

If it does, feel free to close this as I'm leaving for my lectures now.

**Comment by InfinityRaider** [comment] 2015-03-13 17:34
i'm closing this assuming this was a config derp, not a bug. If it still doesn't work, feel free to reopen.

**Closed by InfinityRaider** 2015-03-13 17:34 UTC
Labels: Awaiting reply

**Comment by kotoroshinoto** [comment] 2015-03-13 22:52
i meant to close it with my last message, apologies

**Comment by kotoroshinoto** [comment] 2015-03-13 22:53
I was thinking that if there were no possible mutations, it would simply do a stat boost chance.

**Comment by kotoroshinoto** [comment] 2015-03-13 22:53
Clearly didn't understand the mechanism XD

**Comment by InfinityRaider** [comment] 2015-03-13 23:40
Well its a derpy config setting, giving it a zero will never trigger mutations and setting it to 100 will never trigger spreading
