### ISSUE TITLE
Crash Report - Rendering Block Entity

### ISSUE THREAD

**Issue by Strikes** [InfinityRaider/AgriCraft#686] opened 2016-08-08 00:18 UTC
1.7.10 - Infinity Mod with Magical Crops. 

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 8/7/16 7:13 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at net.minecraft.block.Block.func_149677_c(Block.java:527)
	at com.InfinityRaider.AgriCraft.renderers.PlantRenderer.renderStemPlant(PlantRenderer.java:169)
	at com.InfinityRaider.AgriCraft.farming.cropplant.CropPlantStem.renderPlantInCrop(CropPlantStem.java:60)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderCrop.renderPlant(RenderCrop.java:60)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderCrop.doWorldRender(RenderCrop.java:46)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.renderBlock(RenderBlockBase.java:80)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.func_147500_a(RenderBlockBase.java:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at fastcraft.ab.a(F:201)
	at fastcraft.ak.a(F:475)
	at fastcraft.HC.al(F:50)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.Block.func_149677_c(Block.java:527)
	at com.InfinityRaider.AgriCraft.renderers.PlantRenderer.renderStemPlant(PlantRenderer.java:169)
	at com.InfinityRaider.AgriCraft.farming.cropplant.CropPlantStem.renderPlantInCrop(CropPlantStem.java:60)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderCrop.renderPlant(RenderCrop.java:60)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderCrop.doWorldRender(RenderCrop.java:46)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.renderBlock(RenderBlockBase.java:80)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.func_147500_a(RenderBlockBase.java:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)

-- Block Entity Details --
Details:
	Name: AgriCraft:TileEntity_crop // com.InfinityRaider.AgriCraft.tileentity.TileEntityCrop
	Block type: ID #229 (tile.agricraft:crops // com.InfinityRaider.AgriCraft.blocks.BlockCrop)
	Block data value: 7 / 0x7 / 0b0111
	Block location: World: (356,67,-148), Chunk: (at 4,4,12 in 22,-10; contains blocks 352,0,-160 to 367,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #229 (tile.agricraft:crops // com.InfinityRaider.AgriCraft.blocks.BlockCrop)
	Actual block data value: 7 / 0x7 / 0b0111
Stacktrace:
	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at fastcraft.ab.a(F:201)
	at fastcraft.ak.a(F:475)
	at fastcraft.HC.al(F:50)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Strikes12'/111322, l='MpServer', x=359.30, y=8.37, z=-171.30]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-848,64,942), Chunk: (at 0,4,14 in -53,58; contains blocks -848,0,928 to -833,255,943), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 36387737 game time, 44980528 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 78 total; [EntityPig['Pig'/111369, l='MpServer', x=371.50, y=78.00, z=-199.50], EntityPainting['Painting'/111371, l='MpServer', x=342.00, y=205.00, z=-150.94], EntityPainting['Painting'/111370, l='MpServer', x=340.00, y=204.50, z=-144.06], EntityVillager['Villager'/111373, l='MpServer', x=336.94, y=202.00, z=-149.69], EntityPainting['Painting'/111370, l='MpServer', x=340.00, y=204.50, z=-144.06], EntityVillager['Villager'/111372, l='MpServer', x=336.94, y=202.00, z=-147.00], EntityBat['Bat'/179212, l='MpServer', x=432.25, y=36.10, z=-203.75], EntityVillager['Villager'/111375, l='MpServer', x=355.25, y=207.00, z=-148.50], EntityVillager['Villager'/111374, l='MpServer', x=336.94, y=202.00, z=-145.50], EntityVillager['Villager'/111377, l='MpServer', x=336.94, y=202.00, z=-148.75], EntityVillager['Villager'/111376, l='MpServer', x=336.94, y=202.00, z=-147.84], EntityVillager['Villager'/111378, l='MpServer', x=351.59, y=207.00, z=-146.75], EntitySkeleton['Skeleton'/188950, l='MpServer', x=287.50, y=68.00, z=-246.50], EntitySkeleton['Skeleton'/188951, l='MpServer', x=288.50, y=68.00, z=-245.50], EntityItemFrame['Item Frame'/156180, l='MpServer', x=310.06, y=92.50, z=-130.50], EntityItemFrame['Item Frame'/156181, l='MpServer', x=310.06, y=93.50, z=-130.50], EntityZombie['Zombie'/180762, l='MpServer', x=398.53, y=21.00, z=-226.97], EntitySkeleton['Skeleton'/187416, l='MpServer', x=364.63, y=17.00, z=-228.09], EntityCreeper['Creeper'/180767, l='MpServer', x=397.50, y=20.00, z=-233.50], EntitySkeleton['Skeleton'/180764, l='MpServer', x=399.50, y=20.00, z=-228.50], EntityCreeper['Creeper'/180768, l='MpServer', x=397.50, y=20.00, z=-234.50], EntityZombie['Zombie'/187681, l='MpServer', x=307.50, y=34.00, z=-215.50], EntityZombie['Zombie'/189226, l='MpServer', x=351.50, y=24.00, z=-117.50], EntityZombie['Zombie'/189224, l='MpServer', x=351.50, y=24.00, z=-119.50], EntityZombie['Zombie'/189225, l='MpServer', x=347.50, y=24.00, z=-115.50], EntitySquid['Squid'/170285, l='MpServer', x=418.25, y=50.19, z=-155.88], EntityCartChest['entity.MinecartChest.name'/111410, l='MpServer', x=501.50, y=28.50, z=-29.50], EntityZombie['Zombie'/180282, l='MpServer', x=410.97, y=39.00, z=-217.59], EntityChicken['Chicken'/111419, l='MpServer', x=343.56, y=62.38, z=-223.56], EntityItem['item.item.egg'/181570, l='MpServer', x=346.16, y=48.13, z=-222.56], EntityClientPlayerMP['Strikes12'/111322, l='MpServer', x=359.30, y=8.37, z=-171.30], EntityHat['unknown'/585, l='MpServer', x=359.30, y=8.37, z=-171.30], EntityHat['unknown'/3512673, l='MpServer', x=288.34, y=29.51, z=-169.44], EntitySkeleton['Skeleton'/187227, l='MpServer', x=285.50, y=43.00, z=-228.50], EntityTrail['unknown'/604, l='MpServer', x=359.30, y=8.37, z=-171.30], EntityChicken['Chicken'/110960, l='MpServer', x=427.47, y=62.08, z=-170.53], EntityZombie['Zombie'/187508, l='MpServer', x=347.50, y=21.00, z=-222.50], EntitySkeleton['Skeleton'/181118, l='MpServer', x=388.50, y=21.00, z=-224.50], EntityCreeper['Creeper'/179326, l='MpServer', x=371.66, y=25.00, z=-198.94], EntityCreeper['Creeper'/179327, l='MpServer', x=373.50, y=25.00, z=-200.50], EntityCreeper['Creeper'/167299, l='MpServer', x=415.13, y=38.00, z=-181.22], EntityItem['item.item.1MinicioEssence'/181392, l='MpServer', x=303.88, y=73.13, z=-226.69], EntityZombie['Zombie'/189342, l='MpServer', x=373.50, y=40.00, z=-199.50], EntityZombie['Zombie'/189343, l='MpServer', x=370.50, y=40.00, z=-199.50], EntityPainting['Painting'/111370, l='MpServer', x=340.00, y=204.50, z=-144.06], EntityPainting['Painting'/111371, l='MpServer', x=342.00, y=205.00, z=-150.94], EntityZombie['Zombie'/189344, l='MpServer', x=369.50, y=40.00, z=-197.50], EntitySkeleton['Skeleton'/188582, l='MpServer', x=314.50, y=17.00, z=-108.50], EntityHat['unknown'/2889866, l='MpServer', x=415.13, y=38.00, z=-181.22], EntityBlitz['Blitz'/189358, l='MpServer', x=308.53, y=20.00, z=-117.53], EntityCreeper['Creeper'/187312, l='MpServer', x=289.69, y=25.82, z=-166.50], EntityZombie['Zombie'/189623, l='MpServer', x=427.50, y=21.00, z=-239.50], EntityBat['Bat'/187322, l='MpServer', x=428.67, y=31.76, z=-168.08], EntityZombie['Zombie'/189624, l='MpServer', x=426.50, y=21.00, z=-238.50], EntityBat['Bat'/187321, l='MpServer', x=423.16, y=36.10, z=-174.31], EntityZombie['Zombie'/189625, l='MpServer', x=426.50, y=21.00, z=-237.50], EntityHat['unknown'/3463048, l='MpServer', x=397.50, y=20.00, z=-233.50], EntityHat['unknown'/3463049, l='MpServer', x=373.50, y=25.00, z=-200.50], EntityCreeper['Creeper'/187594, l='MpServer', x=375.38, y=24.00, z=-220.53], EntityZombie['Zombie'/187851, l='MpServer', x=310.50, y=21.00, z=-95.50], EntityCreeper['Creeper'/188623, l='MpServer', x=340.53, y=8.00, z=-126.56], EntityBat['Bat'/182753, l='MpServer', x=428.63, y=21.92, z=-230.00], EntityZombie['Zombie'/184810, l='MpServer', x=382.50, y=16.00, z=-204.50], EntityZombie['Zombie'/184809, l='MpServer', x=378.50, y=15.00, z=-208.03], EntitySkeleton['Skeleton'/188649, l='MpServer', x=378.50, y=71.00, z=-207.50], EntityBat['Bat'/187375, l='MpServer', x=330.13, y=21.89, z=-208.72], EntityBat['Bat'/187378, l='MpServer', x=336.31, y=21.48, z=-225.28], EntityBat['Bat'/187379, l='MpServer', x=337.75, y=21.00, z=-220.72], EntityZombie['Zombie'/187635, l='MpServer', x=331.50, y=49.00, z=-164.50], EntityCreeper['Creeper'/184816, l='MpServer', x=433.50, y=30.00, z=-199.50], EntityBat['Bat'/187376, l='MpServer', x=330.03, y=21.13, z=-207.16], EntityZombie['Zombie'/175350, l='MpServer', x=380.03, y=24.00, z=-195.53], EntityZombie['Zombie'/175351, l='MpServer', x=374.50, y=25.00, z=-200.50], EntitySkeleton['Skeleton'/168693, l='MpServer', x=429.34, y=29.00, z=-202.41], EntityCreeper['Creeper'/184570, l='MpServer', x=382.41, y=38.00, z=-96.06], EntityVillager['Villager'/111356, l='MpServer', x=357.69, y=207.00, z=-146.31], EntitySkeleton['Skeleton'/188671, l='MpServer', x=380.50, y=27.00, z=-220.50], EntityBat['Bat'/187389, l='MpServer', x=288.34, y=29.51, z=-169.44]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by DranKof** [comment] 2016-08-14 20:07
You requested a clean stacktrace in #677 , this is actually a duplicate of #677, #687 is not exactly a duplicate of either of these because it features a stacktrace that goes straight to net.minecraft.client. Not sure if that makes a difference, but I was hoping that you noticed that.

**Comment by InfinityRaider** [comment] 2016-08-14 22:29
You're right the stacktraces arent completely identical, but the exception happens at the same point in the code.
Ill reopen #687 and close this one because of the cleaner stacktrace.

**Closed by InfinityRaider** 2016-08-14 22:29 UTC
Labels: 1.7.10, bug
