### ISSUE TITLE
crash on startup using agricraft for 1.8.9

### ISSUE THREAD

**Issue by thehandsomebaron** [InfinityRaider/AgriCraft#594] opened 2016-03-27 13:57 UTC
i tried adding agricraft to ftb unstable and it crashes almost immediately upon startup. i didnt know if crash reports where being accepted this early on but here it is anyway.

[crash-2016-03-27_14.48.09-client.txt](https://github.com/InfinityRaider/AgriCraft/files/190910/crash-2016-03-27_14.48.09-client.txt)

**Comment by InfinityRaider** [comment] 2016-03-27 14:45
Crash reports are always accepted, however this is a duplicate of #592

**Closed by InfinityRaider** 2016-03-27 14:45 UTC
